### ISSUE TITLE
java.lang.NoSuchFieldException: TABLENAME

### ISSUE THREAD

**Issue by bschnack** [greenrobot/greenDAO#756] opened 2017-08-28 16:21 UTC
Hello,

We are hitting an exception where there is no such field titled TABLENAME. It seems other people have also hit this issue but say it is a device specific issue. 

We have had users hit it on the following phones:
SAMSUNG-SGH-I537
SCH-I545

And the following OS:
5.0.1

Our proguard rules look like: 
```
-keepclassmembers class * extends org.greenrobot.greendao.AbstractDao {
public static java.lang.String TABLENAME;
}
-keep class **$Properties

-dontwarn org.greenrobot.greendao.database.**
-dontwarn rx.**
```

Here is the stack trace and unfortunately some of it got cut off in all of our instances of this crash. Let me know if there is anything else you need to know.

> Caused by: org.greenrobot.greendao.DaoException: Could not init DAOConfig
> 	at org.greenrobot.greendao.internal.DaoConfig.<init>(DaoConfig.java:94)
> 	at org.greenrobot.greendao.AbstractDaoMaster.registerDaoClass(AbstractDaoMaster.java:44)
> 	at ols.microsoft.com.shiftr.model.DaoMaster.<init>(DaoMaster.java:123)
> 	at ols.microsoft.com.shiftr.model.DaoMaster.<init>(DaoMaster.java:107)
> 	at ols.microsoft.com.shiftr.database.GreenDaoImpl.<init>(GreenDaoImpl.java:154)
> 	at ols.microsoft.com.shiftr.service.ShiftrDataService.createDaoInstance(ShiftrDataService.java:395)
> 	at ols.microsoft.com.shiftr.service.ShiftrDataService.onCreate(ShiftrDataService.java:365)
> 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3148)
> 	... 9 more
> Caused by: java.lang.NoSuchFieldException: TABLENAME
> 	at java.lang.Class.getField(Class.java:1104)
> 	at org.greenrobot.greendao.internal.DaoConfig.<init>(DaoConfig.java:56)

**Comment by mishindmitriy** [comment] 2017-09-04 05:33
i have the same issue with the same proguard rules

> `Caused by org.greenrobot.greendao.DaoException: Could not init DAOConfig
>        at org.greenrobot.greendao.internal.DaoConfig.<init>(DaoConfig.java:94)
>        at org.greenrobot.greendao.AbstractDaoMaster.registerDaoClass(AbstractDaoMaster.java:44)
>        at com.clutchpoints.model.entities.DaoMaster.<init>(DaoMaster.java:177)
>        at com.clutchpoints.model.entities.DaoMaster.<init>(DaoMaster.java:153)
>        at com.clutchpoints.app.CPApp.onCreate(CPApp.java:188)
>        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
>        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5122)
>        at android.app.ActivityThread.access$1600(ActivityThread.java:177)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:145)
>        at android.app.ActivityThread.main(ActivityThread.java:5951)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
> Caused by java.lang.NoSuchFieldException: TABLENAME
>        at java.lang.Class.getField(Class.java:1104)
>        at org.greenrobot.greendao.internal.DaoConfig.<init>(DaoConfig.java:56)
>        at org.greenrobot.greendao.AbstractDaoMaster.registerDaoClass(AbstractDaoMaster.java:44)
>        at com.clutchpoints.model.entities.DaoMaster.<init>(DaoMaster.java:177)
>        at com.clutchpoints.model.entities.DaoMaster.<init>(DaoMaster.java:153)
>        at com.clutchpoints.app.CPApp.onCreate(CPApp.java:188)
>        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
>        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5122)
>        at android.app.ActivityThread.access$1600(ActivityThread.java:177)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:145)
>        at android.app.ActivityThread.main(ActivityThread.java:5951)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)`

**Comment by Sirelon** [comment] 2017-09-07 09:02
The same issue. On Samsung with Android 5.

**Comment by greenrobot-team** [comment] 2017-09-12 08:32
This is discussed at length in #188 with some possible solutions. Closing this as duplicate of #188. -ut

**Closed by greenrobot-team** 2017-09-12 08:32 UTC
