### ISSUE TITLE
In Gradle 3.1.0 can not work! 

### ISSUE THREAD

**Issue by JanesenHeart** [greenrobot/greenDAO#846] opened 2018-03-29 13:36 UTC
Failed to resolve: greendao！

**Comment by favsol26** [comment] 2018-03-29 14:16
it's true, the problem that it's shows is:

 Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018

Failed to resolve: greendao

**Comment by KyungminCho** [comment] 2018-03-29 17:17
Same here!!!

**Comment by caprice** [comment] 2018-04-02 01:10
encountered the same issue.

**Comment by MuQi-Jason** [comment] 2018-04-02 02:22
greendao {
        schemaVersion x 
        daoPackage 'xxx' 
        targetGenDir 'xxx
    }
put it in android {} replace in sourceSets{}

**Comment by greenrobot-team** [comment] 2018-04-17 12:17
In your app modules `build.gradle` file try to change
`compile 'org.greenrobot:greendao:3.2.2'`
to
`implementation 'org.greenrobot:greendao:3.2.2'`
-ut

**Comment by greenrobot-team** [comment] 2018-05-07 13:04
Closing due to missing details. Please re-open if you can share a small example project that reproduces this issue. -ut

**Closed by greenrobot-team** 2018-05-07 13:04 UTC
