### ISSUE TITLE
multithreading AbstractDao.deleteAll() cause occasionally Database Lock

### ISSUE THREAD

**Issue by wolongalick** [greenrobot/greenDAO#853] opened 2018-04-17 14:31 UTC
![11111111](https://user-images.githubusercontent.com/5212514/38876578-4f55d8f8-428f-11e8-81f1-0ca6bbdb7558.png)

**Comment by greenrobot-team** [comment] 2018-05-07 13:02
Can you try to get an actual stack trace and the exception type? In any case, make sure that you do not use the database in another process. -ut

**Comment by carson123** [comment] 2018-05-18 08:04
这样try catch 有用没。会不会还出现死锁。

**Comment by greenrobot-team** [comment] 2018-08-21 13:44
Closing due to missing details. Please re-open if you can share a small example project that reproduces this issue. -ut

**Closed by greenrobot-team** 2018-08-21 13:44 UTC
