### ISSUE TITLE
How can i set default boolean value?

### ISSUE THREAD

**Issue by karun2189** [greenrobot/greenDAO#322] opened 2016-03-29 11:22 UTC
I have boolean column in table, i want to set default boolean value. How can i set it?

**Comment by yishai-glide** [comment] 2016-03-29 11:35
this is a duplicate of https://github.com/greenrobot/greenDAO/issues/17

**Comment by greenrobot-team** [comment] 2016-07-04 10:53
Closing, as said above this is tracked in #17.

**Closed by greenrobot-team** 2016-07-04 10:53 UTC
