### ISSUE TITLE
Java.Lang.Object is unresloved its reference indirectly in <Path>/FeedRecord.java

### ISSUE THREAD

**Issue by Zedonboy** [greenrobot/greenDAO#897] opened 2018-08-20 07:11 UTC
I use greendao in Android Studio(WIndows) peacefully no errors.

I switched to Linux Debian with OpenJDK 10
using IntelliJ Idea as IDE, i used the same build.gradle

But am seeing this errors, you have any idea what i did wrong?

**Comment by greenrobot-team** [comment] 2018-08-21 09:27
Do you have more log output or a stack trace? This error does not look like it is caused by greenDAO.

Closing due to missing details. Please re-open if you can share more details on this issue.
-ut

**Closed by greenrobot-team** 2018-08-21 09:27 UTC

**Comment by ahmedakmal525** [comment] 2019-01-22 05:36
@Zedonboy please use Oracle JDK. OpenJDK has some issues with greenDAO. for me OracleJDK works perfect.
To install OracleJDK please follow the instructions in this [link](https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-ubuntu-18-04).
