### ISSUE TITLE
使用sqlcipher和greendao，会出现死锁

### ISSUE THREAD

**Issue by carson123** [greenrobot/greenDAO#868] opened 2018-05-18 06:48 UTC
多线程执行 事务插入大量数据时，容易出现死锁。
如何避免？求帮助！

EN: Multi-threaded execution When a transaction inserts a large amount of data, it is prone to deadlock. How to avoid? please help!

**Comment by greenrobot-team** [comment] 2018-08-21 12:27
Honestly, I don't know. Can you share a small example project that has this issue?

Closing due to missing details. Please re-open if you can share a small example project that reproduces this issue.
-ut

**Closed by greenrobot-team** 2018-08-21 12:27 UTC
