### ISSUE TITLE
Execution failed for task ':examples:DaoExample:greendao'.

### ISSUE THREAD

**Issue by tigerjiang** [greenrobot/greenDAO#998] opened 2019-10-19 08:57 UTC
I execute the gradlew then the error occur as below:
jiangzehus-iMac:greenDAO-master jiangzehu$ ./gradlew clean assembledebug

> Configure project :
Signing information missing/incomplete for DaoCore
Signing information missing/incomplete for DaoGenerator
Signing information missing/incomplete for examples
Signing information missing/incomplete for greendao-api
Signing information missing/incomplete for tests
Signing information missing/incomplete for DaoExample
Signing information missing/incomplete for RxDaoExample
Signing information missing/incomplete for DaoTest
Signing information missing/incomplete for DaoTestBase
Signing information missing/incomplete for DaoTestEntityAnnotation
Signing information missing/incomplete for DaoTestGenerator
Signing information missing/incomplete for DaoTestPerformance

> Configure project :DaoCore
Settings sonatypeUsername/sonatypePassword missing/incomplete for DaoCore

> Configure project :DaoGenerator
Settings sonatypeUsername/sonatypePassword missing/incomplete for DaoGenerator

> Configure project :examples
Settings sonatypeUsername/sonatypePassword missing/incomplete for examples

> Configure project :greendao-api
Settings sonatypeUsername/sonatypePassword missing/incomplete for greendao-api

> Configure project :tests
Settings sonatypeUsername/sonatypePassword missing/incomplete for tests

> Configure project :examples:DaoExample
Settings sonatypeUsername/sonatypePassword missing/incomplete for DaoExample

> Configure project :examples:RxDaoExample
Settings sonatypeUsername/sonatypePassword missing/incomplete for RxDaoExample

> Configure project :tests:DaoTest
Settings sonatypeUsername/sonatypePassword missing/incomplete for DaoTest

> Configure project :tests:DaoTestBase
Settings sonatypeUsername/sonatypePassword missing/incomplete for DaoTestBase

> Configure project :tests:DaoTestEntityAnnotation
Settings sonatypeUsername/sonatypePassword missing/incomplete for DaoTestEntityAnnotation

> Configure project :tests:DaoTestGenerator
Settings sonatypeUsername/sonatypePassword missing/incomplete for DaoTestGenerator

> Configure project :tests:DaoTestPerformance
Settings sonatypeUsername/sonatypePassword missing/incomplete for DaoTestPerformance

> Task :examples:DaoExample:greendao FAILED
Found 6 problem(s) parsing "/Users/jiangzehu/work/greenDAO-master/examples/DaoExample/src/main/java/org/greenrobot/greendao/example/Note.java":
#1 @1: Pb(324) The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files (ID: 16777540; error: true)
#2 @1: Pb(324) The type java.lang.String cannot be resolved. It is indirectly referenced from required .class files (ID: 16777540; error: true)
#3 @1: Pb(324) The type java.lang.Class cannot be resolved. It is indirectly referenced from required .class files (ID: 16777540; error: true)
#4 @30: Pb(143) Implicit super constructor Object() is undefined. Must explicitly invoke another constructor (ID: 134217871; error: true)
#5 @33: Pb(143) Implicit super constructor Object() is undefined. Must explicitly invoke another constructor (ID: 134217871; error: true)
#6 @38: Pb(143) Implicit super constructor Object() is undefined. Must explicitly invoke another constructor (ID: 134217871; error: true)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':examples:DaoExample:greendao'.
> Found 6 problem(s) parsing "/Users/jiangzehu/work/greenDAO-master/examples/DaoExample/src/main/java/org/greenrobot/greendao/example/Note.java". First problem:
  Pb(324) The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files (16777540 at line 1).
  Run gradle with --info for more details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

**Comment by greenrobot-team** [comment] 2020-02-18 13:16
Are you using a newer JDK? Try to explicitly use JDK 8 when compiling.

**Comment by greenrobot-team** [comment] 2020-02-18 13:18
Duplicate of #1014. Closing in favor as it has more details.

**Closed by greenrobot-team** 2020-02-18 13:18 UTC
