### ISSUE TITLE
getId() return null

### ISSUE THREAD

**Issue by LordSuricato** [greenrobot/greenDAO#856] opened 2018-04-21 15:53 UTC
Every time I call objectFromDb.getId() its value is null.

My generator:

`  
        Entity messagesPush = schema.addEntity("MessagePush");
        messagesPush.addIdProperty().autoincrement().primaryKey().unique();
        messagesPush.addIntProperty("itemId");
`

GreenDao v3.2.2

**Comment by greenrobot-team** [comment] 2018-05-07 12:45
Closing due to missing details. Please re-open if you can share a small example project that reproduces this issue. -ut

**Closed by greenrobot-team** 2018-05-07 12:45 UTC
