### ISSUE TITLE
Why DatabaseOpenHelper not override SQLiteOpenHelper(Context context, String name, CursorFactory factory, int version, DatabaseErrorHandler errorHandler)

### ISSUE THREAD

**Issue by Sejen27** [greenrobot/greenDAO#841] opened 2018-03-15 06:48 UTC
Why DatabaseOpenHelper not override SQLiteOpenHelper(Context context, String name, CursorFactory factory, int version, DatabaseErrorHandler errorHandler)

**Comment by greenrobot-team** [comment] 2018-03-20 10:35
Why should it?

Note: You can also do it yourself.
-ut

**Comment by Sejen27** [comment] 2018-04-09 03:02
I want to set errorHandler, but when OpenHelper extends DatabaseOpenHelper，it can not access constructor below：

public SQLiteOpenHelper(Context context, String name, CursorFactory factory, int version,
DatabaseErrorHandler errorHandler)

**Comment by greenrobot-team** [comment] 2019-07-16 13:21
Just noticed this is a duplicate of https://github.com/greenrobot/greenDAO/issues/839.

**Closed by greenrobot-team** 2019-07-16 13:21 UTC
