### ISSUE TITLE
Only import Generated annotation if used

### ISSUE THREAD

**Issue by DHosseiny** [greenrobot/greenDAO#783] opened 2017-11-06 07:05 UTC
I used @Keep in top of constructor when this constructor is exactly similar to generated constructor. but every time i want to push changes to git I see there is a generated annotation import:

```java
    import org.greenrobot.greendao.annotation.Entity;
    import org.greenrobot.greendao.annotation.Id;
    import org.greenrobot.greendao.annotation.Index;
    import org.greenrobot.greendao.annotation.Keep;
    import org.greenrobot.greendao.annotation.Generated;

    @Entity(
            indexes = {
                    @Index(value = "fileName")
            }
    )
    public class Image {

    public int uid;
    @Id
    public long fileID;
    public String fileName;

    public Image() {
    }

    @Keep
    public Image(int uid, long fileID, String fileName) {
        this.uid = uid;
        this.fileName = fileName;
        this.fileID = fileID;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public int getUid() {
        return this.uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    public long getFileID() {
        return this.fileID;
    }

    public void setFileID(long fileID) {
        this.fileID = fileID;
    }
```

**Comment by greenrobot-team** [comment] 2018-03-27 12:11
Duplicate of #481 -ut

**Closed by greenrobot-team** 2018-03-27 12:11 UTC
