### ISSUE TITLE
Android 9.0 Greendao test build failed.

### ISSUE THREAD

**Issue by CooperCao** [greenrobot/greenDAO#953] opened 2019-03-16 03:29 UTC
DbTest.java 
import android.test.AndroidTestCase;

[https://developer.android.com/reference/android/test/AndroidTestCase](url)
This class was deprecated in API level 24.
Use InstrumentationRegistry instead. New tests should be written using the Android Testing Support Library.

**Comment by greenrobot-team** [comment] 2019-04-01 13:30
Duplicate of https://github.com/greenrobot/greenDAO/issues/936

**Closed by greenrobot-team** 2019-04-01 13:30 UTC
