### ISSUE TITLE
Support Jack toolchain / Java 1.8

### ISSUE THREAD

**Issue by TheBlusky** [greenrobot/greenDAO#407] opened 2016-08-18 20:43 UTC
Hello,
I am new with greenDAO.
I am running with Java 1.8 (Jack enabled).

When trying to compile the APK files are not generated, so I get the following error :

> Error:D:\Developpement\AndroidStudio\StashMobile\app\src\main\java\pm\stash\stashmobile\StashMobile.java:9: The import pm.stash.stashmobile.database.models.DaoMaster cannot be resolved
> Error:D:\Developpement\AndroidStudio\StashMobile\app\src\main\java\pm\stash\stashmobile\StashMobile.java:26: DaoSession cannot be resolved to a type
> Error:D:\Developpement\AndroidStudio\StashMobile\app\src\main\java\pm\stash\stashmobile\StashMobile.java:31: DaoMaster cannot be resolved to a type
> Error:D:\Developpement\AndroidStudio\StashMobile\app\src\main\java\pm\stash\stashmobile\StashMobile.java:33: DaoMaster cannot be resolved to a type
> Error:D:\Developpement\AndroidStudio\StashMobile\app\src\main\java\pm\stash\stashmobile\StashMobile.java:37: DaoSession cannot be resolved to a type

If I manually run the graddle task "greendao", "DaoMaster", "DaeSession" and DAO files are correctly generated. But then, compilation give the following error :

> Information:Gradle tasks [:app:assembleDebug]
> Error:Library reading phase: file 'D:\Developpement\AndroidStudio\StashMobile\app\build\intermediates\packaged\debug\classes.zip' is an invalid library
> Error:com.android.jack.JackAbortException: Library reading phase: file 'D:\Developpement\AndroidStudio\StashMobile\app\build\intermediates\packaged\debug\classes.zip' is an invalid library
> Error:com.android.jack.library.LibraryReadingException: Library reading phase: file 'D:\Developpement\AndroidStudio\StashMobile\app\build\intermediates\packaged\debug\classes.zip' is an invalid library
> Error:com.android.jack.library.LibraryFormatException: file 'D:\Developpement\AndroidStudio\StashMobile\app\build\intermediates\packaged\debug\classes.zip' is an invalid library
> Error:Execution failed for task ':app:transformJackWithJackForDebug'.
> 
> > com.android.build.api.transform.TransformException: com.android.jack.api.v01.CompilationException: Library reading phase: file 'D:\Developpement\AndroidStudio\StashMobile\app\build\intermediates\packaged\debug\classes.zip' is an invalid library
> > Information:BUILD FAILED
> > Information:Total time: 0.925 secs

Is there anything I missed ? I really don't know how to debug this.

Thanks :-)

**Comment by greenrobot-team** [comment] 2016-08-22 12:56
Does this also happen with Jack disabled (you will likely have to disable Java 8 support)? I assume Jack is the root cause as it changes how the toolchain works. We will likely have to udpate the plugin to add Jack support.

```groovy
jackOptions {
    enabled false
}
```
-ut

**Comment by TheBlusky** [comment] 2016-08-22 20:33
Hello !
Finally, I removed Jack options, disabled Java 8, and now it's working fine.
I guess there is currently no ORM working with Jack and Java 8 :-)

Thanks again !

**Comment by greenrobot-team** [comment] 2016-08-23 05:31
We probably still want to have a look at Jack support in the future, reopening. -ut

**Comment by Freesword** [comment] 2016-09-18 08:15
hi! how to resolve this problem? i have the same problem with u

**Comment by greenrobot-team** [comment] 2016-09-19 06:41
@Freesword As said, the greenDAO Gradle plugin currently does not support Jack. You will have to stick to [using javac and Java 7](https://github.com/greenrobot/greenDAO/issues/407#issuecomment-241540971). -ut

**Comment by bmax-moblin** [comment] 2016-09-20 08:51
I managed to build my project with Jack and Java 8 after moving the generated classes (DaoMaster, DaoSession, xxxDAO) to 'src/main/java'. So, i guess it refuses to see custom generated/source files.

**Comment by greenrobot-team** [comment] 2016-11-15 06:40
This should be fixed with the next update where we include the generated sources and the greendao task differently. -ut

**Closed** 2016-11-15 10:11 UTC
Labels: Confirmed

**Comment by jmendezv** [comment] 2016-11-16 08:02
Same issue here :(

**Comment by Reakleases** [comment] 2016-12-12 20:03
@jmendezv , do you use rxbinding?

**Comment by greenrobot-team** [comment] 2016-12-13 06:14
@jmendezv @Reakleases This should no longer be an issue with `classpath 'org.greenrobot:greendao-gradle-plugin:3.2.1'`. Do you still have problems? Please get us a small example project so we can reproduce the issue. -ut

**Comment by Reakleases** [comment] 2016-12-16 10:44
yes I had problem till rxbinding was in dependency of project(3.2.1 included)

**Comment by irshadsparky** [comment] 2017-05-17 13:27
i found solution in my case there is a red error in my code which is not show in compile time.when i see my full code it have a miner mistake so i repared it and it work .

**Comment by ULooper** [comment] 2018-04-28 07:05
what should  i do

**Comment by greenrobot-team** [comment] 2018-05-07 13:43
Jack is officially dead and replaced by Java 8 desugaring. Please submit a new issue if there are issues with the [new Android Java 8 support](https://developer.android.com/studio/write/java8-support). -ut
