### ISSUE TITLE
version file is missing

### ISSUE THREAD

**Issue by w401634075** [greenrobot/greenDAO#893] opened 2018-08-08 12:56 UTC
new DaoGenerator()   error    
debug get exception Version file is missing.
![image](https://user-images.githubusercontent.com/12705057/43838284-818973ae-9b4d-11e8-989c-1ca8cc887a9b.png)

**Comment by w401634075** [comment] 2018-08-09 02:00
"freemarker/version.properties" missing  .   while I upload  freemarker jar to maven .   this problem get.  how can i fix it ?

**Comment by greenrobot-team** [comment] 2018-08-21 09:53
I can't reproduce this issue. Check that you do **not** include a custom version of the `org.freemarker:freemarker` artifact.

Closing due to missing details. Please re-open if you can share a small example project that reproduces this issue.
-ut

**Closed by greenrobot-team** 2018-08-21 09:53 UTC
