### ISSUE TITLE
download greendao-api failed when i used com.android.tools.build:gradle:3.1.0 and distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

### ISSUE THREAD

**Issue by lohago** [greenrobot/greenDAO#844] opened 2018-03-29 07:57 UTC
How can i make it if i want to use the latest gradle version

**Comment by greenrobot-team** [comment] 2018-05-07 13:08
Closing due to missing details. Please re-open if you can share a small example project that reproduces this issue. -ut

**Closed by greenrobot-team** 2018-05-07 13:08 UTC
