### ISSUE TITLE
Add supporting of non exclusive transactions

### ISSUE THREAD

**Issue by kostya29** [greenrobot/greenDAO#315] opened 2016-03-21 10:37 UTC
Can you add supporting of non exclusive transactions?
A lot of mobile applications require non-blocking reading from database to display ui in the same time when sync service update database in own thread.
Thanks!

**Comment by greenrobot-team** [comment] 2016-05-09 12:58
Duplicate of #159

**Closed by greenrobot-team** 2016-05-09 12:58 UTC
Labels: Duplicate
